spring.application.name=service-config
server.port=8888

# Configuration pour utiliser les fichiers embarqués dans le projet
spring.cloud.config.server.native.search-locations=classpath:/config/
spring.profiles.active=native
